# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 901722333d441558e7a738c2d21beace3f7ef190b24f9af44254f46385f550bdbe24d9e1de0656198b7e52f5d0f555857a7e8e4a1e1961f1bb4d1a89a0b7d908

test:
  secret_key_base: 5ec4f7c413c6849049977f22b0047faad7fe7fe7f1c6077b9bcfe0337f7727749b5ec2652dbed051987fdbfffec96674bdfe633204d486423ee576c5b38bd0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
